# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       nodejs

# >> macros
# << macros

Summary:    Evented I/O for V8 JavaScript
Version:    0.0.0
Release:    0
Group:      Development/Languages
License:    MIT
URL:        http://www.nodejs.org
Source0:    %{name}-%{version}.tar.gz
Source100:  nodejs.yaml
BuildRequires:  pkgconfig(zlib)
BuildRequires:  curl
BuildRequires:  gcc-c++
BuildRequires:  procps
BuildRequires:  pkgconfig
BuildRequires:  python
Provides:   npm = %{version}

%description
Provides an easy way to build scalable network programs
http://nodejs.org


%package devel
Summary:    Devel
Group:      Development/Languages
Requires:   %{name} = %{version}-%{release}

%description devel
Provides an easy way to build scalable network programs
http://nodejs.org
This package provides developement headers


%package npm
Summary:    Node package manager
Group:      Development/Languages
Requires:   %{name} = %{version}-%{release}

%description npm
Provides an easy way to build scalable network programs
http://nodejs.org
This package provides npm


%package doc
Summary:    Doc
Group:      Development/Languages
Requires:   %{name} = %{version}-%{release}

%description doc
Provides an easy way to build scalable network programs
http://nodejs.org
This package provides documentation


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
./configure --prefix=/usr --dest-cpu=arm --dest-os=linux --shared-zlib
# << build pre


make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_bindir}/node
%{_libdir}/node_modules
%{_datadir}/systemtap
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_includedir}/node
# >> files devel
# << files devel

%files npm
%defattr(-,root,root,-)
%attr(755,root,root) %{_bindir}/npm
%exclude %{_libdir}/node_modules/npm/.npmignore
%exclude %{_libdir}/node_modules/npm/scripts/clean-old.sh
%exclude %{_libdir}/node_modules/npm/scripts/install.sh
%attr(755,root,root) %{_libdir}/node_modules/npm/scripts/clean-old.sh
%attr(755,root,root) %{_libdir}/node_modules/npm/scripts/install.sh
# >> files npm
# << files npm

%files doc
%defattr(-,root,root,-)
%{_mandir}/*/*
%doc AUTHORS LICENSE
# >> files doc
# << files doc
